kind: pipeline
type: kubernetes
name: default
steps:
  - name: build
    image: gradle:8-jdk21-alpine
    environment:
      PUB_USER:
        from_secret: PUB_USER
      PUB_PASS:
        from_secret: PUB_PASS
    commands:
      - gradle build
      - gradle publish -PpubUsername=$PUB_USER -PpubPassword=$PUB_PASS -PpubUrl=https://maven.wallentines.org/