[versions]
netty = "4.1.105.Final"
mdcfg = "2.4.0"
slf4j = "2.0.11"
jbr-anno = "24.0.1"

[libraries]
netty-buffer = { module = "io.netty:netty-buffer", version.ref = "netty" }
netty-codec = { module = "io.netty:netty-codec", version.ref = "netty" }
netty-codec-dns = { module = "io.netty:netty-codec-dns", version.ref = "netty" }
netty-codec-haproxy = { module = "io.netty:netty-codec-haproxy", version.ref = "netty" }
netty-common = { module = "io.netty:netty-common", version.ref = "netty" }
netty-handler = { module = "io.netty:netty-handler", version.ref = "netty" }
midnight-cfg = { module = "org.wallentines:midnightcfg-api", version.ref="mdcfg" }
midnight-cfg-json = { module = "org.wallentines:midnightcfg-codec-json", version.ref="mdcfg" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref="jbr-anno" }

